name: Daily Trends Fetcher

on:
  schedule:
    # Runs at 00:00 UTC (5:30 AM IST) every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run it manually from the UI

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - name: Run Fetch Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEWS_API_KEY: ${{secrets.NEWS_API_KEY}}
        run: node Fetch_Trends.js # Replace with your actual filename
